### PR TITLE
[DOC] Update install.rst to reflect pyproject.toml

### PR DESCRIPTION
**Pull request by JonathanShor**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-connectivity/blob/main/CONTRIBUTING.md)

PR Description
--------------

Updates the Installation docs page to reflect the current pyproject.toml defined dependencies.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Review by drammock — APPROVED** [review]

**Comment by adam2392** [comment]
I think the CI issue arises from sphinx version I guess? 

@larsoner have you seen this error before?

**Comment by larsoner** [comment]
the short term solution is

https://github.com/mne-tools/mne-python/blob/156ae18572c8322ae75c964258f3fdc607006587/doc/conf.py#L809

the long term solution is 

https://github.com/sphinx-gallery/sphinx-gallery/pull/1289

and other conf.py changes

**Review by adam2392 — APPROVED** [review]
LGTM once CI gets fixed

**Comment by adam2392** [comment]
Thanks @JonathanShor !

**Pull request merged**
