### PR TITLE
[MAINT] Run black, isort, ruff, and other auto-linters on entire package

### PR DESCRIPTION
**Pull request by adam2392**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-connectivity/blob/main/CONTRIBUTING.md)

PR Description
--------------

- runs isort and black formatters

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by larsoner** [comment]
Nowadays in MNE-Python we use pre-commit.ci + .pre-commit-config.yaml to do most style stuff.

For `git` history it would be best to split this PR into two -- one that runs `black` and `isort` and makes `yamllint` changes with whatever settings you want, and you squash+merge that.

Then in a (much smaller!) follow-up PR you add that commit hash to a new `.git-blame-ignore-revs` and adjust CIs. Then `git blame` should be correct on everything.

**Comment by adam2392** [comment]
Okay, I'll do all the yaml/toml stuff first in one go, since those are just extra files and then do the whole package black/ruff/isort as you suggest?

**Comment by larsoner** [comment]
Sure that would work

**Comment by adam2392** [comment]
@larsoner do I update the git-blame file after I merge this PR?

**Pull request merged**
