### PR TITLE
[CI] Fix CIs

### PR DESCRIPTION
**Pull request by adam2392**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-connectivity/blob/main/CONTRIBUTING.md)

PR Description
--------------

Describe your PR here

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by adam2392** [comment]
This will fix the CI issues in #163 

cc: @tsbinns and @orabe

**Comment by adam2392** [comment]
There is just one circleCI failure related to getting `dipy` sphinx objects imported.

Otw, this is good for review/approval

**Comment by larsoner** [comment]
Looks like you need to update the URL to https://docs.dipy.org/1.8.0

**Comment by tsbinns** [comment]
Brilliant, thanks @adam2392!

**Pull request merged**
