### PR TITLE
ENH: Add symmetric orthogonalization

### PR DESCRIPTION
**Pull request by larsoner**
This implements symmetric orthogonalization following https://www.sciencedirect.com/science/article/pii/S1053811915002670.

@agramfort @dengemann @SherazKhan any thoughts on the utility of this versus the already-implemented pairwise orthogonalization? It seems to have the limitation of requiring n_labels < rank, but some advantages mentioned in the paper above (better sensitivity / fewer false alarms among them).

### CODE REVIEW

**Comment by dengemann** [comment]
@larsoner cool! Once it is implemented we should try to understand its benefits :)

**Comment by larsoner** [comment]
> Once it is implemented we should try to understand its benefits :)

It's implemented here, feel free to try it out on some data

**Review by agramfort — COMMENTED** [review]
yes this technique as a constraints on the rank of the data. I think it's still a useful and accepted approach in the community.

I have not checked the numerics.

**Comment by SherazKhan** [comment]
This method is indeed valid and has been used in multiple application papers.

**Comment by larsoner** [comment]
https://253-369628653-gh.circle-artifacts.com/0/dev/auto_examples/mne_inverse_envelope_correlation.html

**Review by agramfort — APPROVED** [review]

**Review by adam2392 — APPROVED** [review]

**Review by adam2392 — APPROVED** [review]

**Pull request merged**
