### PR TITLE
MAINT: Update for 1.2 and bump version

### PR DESCRIPTION
**Pull request by larsoner**
@adam2392 we need to remove `_get_args` to comply with 1.2's removal of it. @adam2392 could you merge this if happy and cut a 0.4.0 release?

cc @drammock this one needed an update due to `_get_args`

### CODE REVIEW

**Review by adam2392 — APPROVED** [review]
Thanks!

**Comment by adam2392** [comment]
I'll try to do a release later today!

**Comment by larsoner** [comment]
@adam2392 just a friendly reminder to cut a release when you get a chance

**Comment by adam2392** [comment]
Done!

**Comment by adam2392** [comment]
Thanks!

**Pull request merged**
