### PR TITLE
[ENH, MRG] remove duplicated code, add deprecation for subplot indexing [skip ci

### PR DESCRIPTION
**Pull request by alexrockhill**
This brings mne-connectivity up to date with changes to connectivity plotting and prevents getting out of sync in the future. Adds a few features from https://github.com/mne-tools/mne-python/pull/10439.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [x] PR title starts with [MRG]
- [x] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by alexrockhill** [comment]
Not sure what's going on with Circle, it looks like some kind of permissions error but otherwise this should be good

cc @adam2392

**Comment by alexrockhill** [comment]
Since Circle isn't running, I just ran the examples locally and got some deprecation warnings so I fixed those too

**Review by adam2392 — COMMENTED** [review]
Will take a look at:

`examples/mixed_source_space_connectivity.py` and `examples/mne_inverse_label_connectivity.py` when circleCI done.

**Comment by alexrockhill** [comment]
It looks good on the previous ones but probably wait until circle finishes https://497-369628653-gh.circle-artifacts.com/0/dev/auto_examples/mne_inverse_label_connectivity.html

**Review by adam2392 — APPROVED** [review]

**Pull request merged**
