### PR TITLE
[CI] Check reqs

### PR DESCRIPTION
**Pull request by adam2392**
Thanks for contributing. If this is your first time,
make sure to read [contributing.md](https://github.com/mne-tools/mne-connectivity/blob/main/CONTRIBUTING.md)

PR Description
--------------

Describe your PR here

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Comment by adam2392** [comment]
Any chance you guys know what is up w/ the CI?

**Comment by drammock** [comment]
pushed a commit that should hopefully fix it. FYI the error was coming during PyVistaQt installation, and said

> Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
> 
> For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

so I `git grep`ped for `git+https` which quickly led to `tools/circleci_dependencies.sh`

**Review by drammock — APPROVED** [review]
PR description is missing, so I'm approving on the assumption that the goal here is just to align with upstream MNE-Python deps. Is that right @adam2392?

**Comment by adam2392** [comment]
> PR description is missing, so I'm approving on the assumption that the goal here is just to align with upstream MNE-Python deps. Is that right @adam2392?

Yep!

**Comment by drammock** [comment]
Install step succeeds now, but hitting this in `mne_sys_info` step:

```
Visualization (optional)
├☑ pyvista           0.39.dev0 (OpenGL 4.5 (Core Profile) Mesa 22.2.5 via llvmpipe (LLVM 15.0.6, 256 bits))
├☑ pyvistaqt         0.11.0.dev16+gea2968e
├☑ vtk               9.2.6
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

/bin/bash: line 2:  3185 Aborted                 (core dumped) python -c "import mne; mne.sys_info()"

Exited with code exit status 134
```
rerunning with SSH to see if I can sort it without @larsoner's help for once :)

**Comment by drammock** [comment]
OK I've faffed about for too long on this with no progress.  @larsoner how do we fix 
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

Aborted (core dumped)
```
I SSHd into circle and it's not even showing any `/usr/lib/x86_64-linux-gnu/libq*` or `/usr/lib/x86_64-linux-gnu/libQ*` libraries (the standard advice on the Qt forums is to run `ldd` on the relevant plugin `.so` and look for missing dependencies)

**Comment by larsoner** [comment]
... Qt occasionally changes its OS deps and in this case I think the culprit was `libxcursor0` or something. But still better to remove the `setup_xvfb.sh` from here rather than just add it

**Pull request merged**
