### PR TITLE
[ENH] Added n_con arg to function call

### PR DESCRIPTION
**Pull request by Avoide**
PR Description
--------------

Moved the hard-coded variable n_con to be one of the arguments for the function call. To enable choosing the number of connections shown, instead of always 20. Added a default option, to make it compatible with previous usage.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/mne-tools/mne-connectivity/blob/main/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

### CODE REVIEW

**Review by adam2392 — APPROVED** [review]
Can you fix the style error in `make pep`?

You'll need to install flake8, pydocstyle and codespell

**Comment by Avoide** [comment]
I fixed the style errors associated with the file I changed, but the test is not passing due to errors in two other files:
envelope.py and smooth.py.
I already corrected those codespell errors in my other PR, but does it make sense to also correct in this PR?

**Comment by adam2392** [comment]
> I already corrected those codespell errors in my other PR, but does it make sense to also correct in this PR?

Now that I've merged in the other PR, you can "rebase your changes on top of main", or "merge in main". Lmk if you don't know how to do that.

Can you also add a changelog entry to `doc/whats_new.rst`? You can see the previous releases file for a format of how to do so.

**Comment by adam2392** [comment]
Oh actually, I forgot I can just merge in `main` from the PR itself here with a button click, so now you can just run `git pull` to get the latest changes on your branch

**Comment by Avoide** [comment]
Thanks, I updated whats_net and added an entry into authors. Hopefully the link should work.

**Comment by adam2392** [comment]
Thanks @Avoide !

**Pull request merged**
